version: 2

sources:
  - name: accounts
    database: analytics-take-home-test  
    schema: monzo_datawarehouse  
    tables:
      - name: account_created
      - name: account_closed
      - name: account_reopened
      - name: account_transactions